Output distinct-light.gif
Set FontFamily "JetBrainsMono Nerd Font"
Set FontSize 22
Set Width 1300
Set Height 650
Set Padding 10
Set TypingSpeed 50ms
Set Theme {"name":"Vetrina Light","black":"#5c5f77","red":"#d20f39","green":"#40a02b","yellow":"#df8e1d","blue":"#1e66f5","magenta":"#ea76cb","cyan":"#179299","white":"#acb0be","brightBlack":"#6c6f85","brightRed":"#d20f39","brightGreen":"#40a02b","brightYellow":"#df8e1d","brightBlue":"#1e66f5","brightMagenta":"#ea76cb","brightCyan":"#179299","brightWhite":"#bcc0cc","background":"#f4f4f5","foreground":"#1a1a1a","cursor":"#1a1a1a","cursorAccent":"#f4f4f5","selection":"#acb0be"}

Set TypingSpeed 20ms

Type "# the new distinct feature allows you to control cardinality!"
Enter

Sleep 1s

Type "fakedata --seed 42 -n 8 uuidv4 order_id:distinct:3:uuidv4"
Enter

Sleep 1s

Type "# ✨ Easy eh? Check it out on matto.club/vetrina/fakedata  🎉"
Enter

Sleep 2s
