blank_issues_enabled: true
contact_links:
  - name: Club Matto Discussions
    url: https://github.com/clubmatto/vetrina/discussions
    about: Please ask questions, start discussions, and share ideas here.
