package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

const (
	dirPerm  = os.FileMode(0777)
	filePerm = os.FileMode(0644)
)

// relative package data dir.
const targetDir = "data"

// Content of a Go file.
const fileTemplate = `// Code generated by tools/import/corpora.go; DO NOT EDIT.

package data

var %s = %#v
`

var keyExtractor = func(key string) func(io.ReadCloser) []string {
	return func(body io.ReadCloser) []string {
		var jsonData map[string]json.RawMessage
		if err := json.NewDecoder(body).Decode(&jsonData); err != nil {
			log.Fatal(err)
		}

		var data []string
		if err := json.Unmarshal(jsonData[key], &data); err != nil {
			log.Fatal(err)
		}

		return data
	}
}

var tasks = []struct {
	URL       string
	Extractor func(io.ReadCloser) []string
	Var       string
}{
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/foods/fruits.json",
		keyExtractor("fruits"),
		"Fruits",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/foods/vegetables.json",
		keyExtractor("vegetables"),
		"Vegetables",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/foods/fish.json",
		keyExtractor("fish"),
		"Fish",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/foods/herbs_n_spices.json",
		func(body io.ReadCloser) []string {
			var jsonData struct {
				Herbs  []string `json:"herbs"`
				Spices []string `json:"spices"`
			}
			if err := json.NewDecoder(body).Decode(&jsonData); err != nil {
				log.Fatal(err)
			}

			return append(jsonData.Herbs, jsonData.Spices...)
		},
		"Spice",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/foods/tea.json",
		keyExtractor("teas"),
		"Tea",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/plants/flowers.json",
		keyExtractor("flowers"),
		"Flowers",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/plants/plants.json",
		func(body io.ReadCloser) []string {
			var jsonData struct {
				Plants []struct {
					Name string `json:"name"`
				} `json:"plants"`
			}
			if err := json.NewDecoder(body).Decode(&jsonData); err != nil {
				log.Fatal(err)
			}
			data := make([]string, len(jsonData.Plants))
			for i, p := range jsonData.Plants {
				data[i] = p.Name
			}

			return data
		},
		"Plants",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/sports/sports.json",
		keyExtractor("sports"),
		"Sports",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/music/instruments.json",
		keyExtractor("instruments"),
		"Instruments",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/music/genres.json",
		keyExtractor("genres"),
		"MusicGenres",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/mythology/greek_gods.json",
		keyExtractor("greek_gods"),
		"GreekGods",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/mythology/roman_deities.json",
		keyExtractor("roman_deities"),
		"RomanDeities",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/mythology/monsters.json",
		keyExtractor("names"),
		"Monsters",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/art/isms.json",
		keyExtractor("isms"),
		"ArtMovements",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/materials/metals.json",
		keyExtractor("metals"),
		"Metals",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/materials/fabrics.json",
		keyExtractor("fabrics"),
		"Fabrics",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/materials/packaging.json",
		keyExtractor("packaging"),
		"Packaging",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/materials/scents.json",
		keyExtractor("scent"),
		"Scents",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/science/planets.json",
		func(body io.ReadCloser) []string {
			var jsonData struct {
				Planets []struct {
					Name string `json:"name"`
				} `json:"planets"`
			}
			if err := json.NewDecoder(body).Decode(&jsonData); err != nil {
				log.Fatal(err)
			}
			data := make([]string, len(jsonData.Planets))
			for i, p := range jsonData.Planets {
				data[i] = p.Name
			}

			return data
		},
		"Planets",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/science/weather_conditions.json",
		keyExtractor("conditions"),
		"WeatherConditions",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/technology/programming_languages.json",
		func(body io.ReadCloser) []string {
			var data []string
			if err := json.NewDecoder(body).Decode(&data); err != nil {
				log.Fatal(err)
			}

			return data
		},
		"ProgrammingLanguages",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/words/nouns.json",
		keyExtractor("nouns"),
		"Nouns",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/animals/common.json",
		keyExtractor("animals"),
		"Animals",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/animals/dinosaurs.json",
		keyExtractor("dinosaurs"),
		"Dinosaurs",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/animals/dogs.json",
		keyExtractor("dogs"),
		"Dogs",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/animals/cats.json",
		keyExtractor("cats"),
		"Cats",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/words/emoji/emoji.json",
		keyExtractor("emoji"),
		"Emoji",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/words/adjs.json",
		keyExtractor("adjs"),
		"Adjectives",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/words/common.json",
		func(body io.ReadCloser) []string {
			var jsonData struct {
				CommonWords []string `json:"commonWords"`
			}
			if err := json.NewDecoder(body).Decode(&jsonData); err != nil {
				log.Fatal(err)
			}

			return jsonData.CommonWords
		},
		"Words",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/words/harvard_sentences.json",
		keyExtractor("data"),
		"Sentences",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/corporations/industries.json",
		keyExtractor("industries"),
		"Industries",
	},
	{
		"https://raw.githubusercontent.com/dariusk/corpora/master/data/humans/occupations.json",
		keyExtractor("occupations"),
		"Occupations",
	},
}

func importCorpora() {
	// Check if running in the repository directory
	_, err := os.Stat(targetDir)
	if err != nil && !os.IsNotExist(err) {
		log.Fatal(err)
	}

	if err != nil {
		log.Fatalf("the data directory cannot be found at %s. Ensure the importer is running in the correct location: %v",
			targetDir, err)
	}

	for _, task := range tasks {
		// Get JSON from URL
		var resp *http.Response

		resp, err = http.Get(task.URL)
		if err != nil {
			log.Fatal(err)
		}

		file := filepath.Join(targetDir, strings.ToLower(task.Var)+".go")
		if err = os.MkdirAll(filepath.Dir(file), dirPerm); err != nil {
			log.Fatal(err)
		}

		data := task.Extractor(resp.Body)

		content := fmt.Sprintf(fileTemplate, task.Var, data)

		if err = os.WriteFile(file, []byte(content), filePerm); err != nil {
			log.Fatal(err)
		}

		if err = resp.Body.Close(); err != nil {
			panic(err)
		}
	}
}
