package main

import (
	"bytes"
	"log"
	"os"
	"path/filepath"
	"text/template"
)

const goFileTemplate = `// Code generated by {{.Tool}}; DO NOT EDIT.

package data

{{range .Blocks}}{{.}}

{{end}}`

var goFileTmpl = template.Must(template.New("gofile").Parse(goFileTemplate))

type GeneratedFile struct {
	Tool   string
	Blocks []string
}

func writeGenerated(dir, filename string, f GeneratedFile) {
	var buf bytes.Buffer
	if err := goFileTmpl.Execute(&buf, f); err != nil {
		log.Fatal(err)
	}

	if err := os.MkdirAll(dir, dirPerm); err != nil {
		log.Fatal(err)
	}

	file := filepath.Join(dir, filename)
	if err := os.WriteFile(file, buf.Bytes(), filePerm); err != nil {
		log.Fatal(err)
	}

	log.Printf("Written %s\n", file)
}
