// Code generated by tools/import/corpora.go; DO NOT EDIT.

package data

var GreekGods = []string{"Aphrodite", "Apollo", "Ares", "Artemis", "Athena", "Demeter", "Dionysus", "Hades", "Hephaestus", "Hera", "Hermes", "Hestia", "Poseidon", "Zeus", "Aether", "Ananke", "Chaos", "Chronos", "Erebus", "Eros", "Hypnos", "Uranus", "Gaia", "Phanes", "Pontus", "Tartarus", "Thalassa", "Thanatos", "Hemera", "Nyx", "Nemesis"}
