// Code generated by tools/import/corpora.go; DO NOT EDIT.

package data

var Packaging = []string{"aluminium foil", "bopet", "bubble wrap", "cellophane", "corrugated fiberboard", "corrugated plastic", "cushioning", "foam peanut", "glass", "hot-melt adhesive", "kraft paper", "linear low-density polyethylene", "liquid packaging board", "low-density polyethylene", "metallised film", "modified atmosphere", "molded pulp", "nonwoven fabric", "paperboard", "plastic film", "plastic wrap", "polyester", "polyethylene", "polypropylene", "shrinkwrap", "tinplate", "velostat"}
