// Code generated by tools/import/corpora.go; DO NOT EDIT.

package data

var Planets = []string{"Mercury", "Venus", "Earth", "Mars", "Ceres", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", "Haumea", "Makemake", "Eris"}
