// Code generated by tools/import/corpora.go; DO NOT EDIT.

package data

var RomanDeities = []string{"Apollo", "Bacchus", "Caelus", "Ceres", "Cupid", "Diana", "Fortuna", "Janus", "Juno", "Jupiter", "Mars", "Mercury", "Minerva", "Neptune", "Nox", "Pluto", "Proserpina", "Saturn", "Sol Invictus", "Spes", "Terra", "Venus", "Veritas", "Vesta", "Vulcan"}
